/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodtrucktracker;

/**
 *
 * @author Mridhula Vijayakumar
 */
public class GUI extends javax.swing.JFrame {
    
    FoodTruckList truckList = new FoodTruckList();
    RecentTruckStack truckStack = new RecentTruckStack();
    OrderQueue orderQueue = new OrderQueue();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        truckNameLbl = new javax.swing.JLabel();
        cuisineLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        ownerLbl = new javax.swing.JLabel();
        regNoLbl = new javax.swing.JLabel();
        positionLbl = new javax.swing.JLabel();
        truckNameTF = new javax.swing.JTextField();
        cuisineTF = new javax.swing.JTextField();
        locationTF = new javax.swing.JTextField();
        ownerTF = new javax.swing.JTextField();
        regNoTF = new javax.swing.JTextField();
        positionTF = new javax.swing.JTextField();
        addTruckBtn = new javax.swing.JButton();
        viewAllBtn = new javax.swing.JButton();
        updateTruckBtn = new javax.swing.JButton();
        deleteTruckBtn = new javax.swing.JButton();
        viewStackBtn = new javax.swing.JButton();
        viewQueueBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setText("Smart Docklands Food Truck Tracker");

        truckNameLbl.setText("Truck Name :");

        cuisineLbl.setText("Cuisine :");

        locationLbl.setText("Location :");

        ownerLbl.setText("Owner :");

        regNoLbl.setText("Reg No :");

        positionLbl.setText("Position :");

        truckNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckNameTFActionPerformed(evt);
            }
        });

        addTruckBtn.setText("Add Truck");
        addTruckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTruckBtnActionPerformed(evt);
            }
        });

        viewAllBtn.setText("View All");
        viewAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBtnActionPerformed(evt);
            }
        });

        updateTruckBtn.setText("Update Truck");
        updateTruckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTruckBtnActionPerformed(evt);
            }
        });

        deleteTruckBtn.setText("Delete Truck");
        deleteTruckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTruckBtnActionPerformed(evt);
            }
        });

        viewStackBtn.setText("View Stack");
        viewStackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStackBtnActionPerformed(evt);
            }
        });

        viewQueueBtn.setText("View Queue");
        viewQueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQueueBtnActionPerformed(evt);
            }
        });

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        jScrollPane1.setViewportView(displayTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(positionLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regNoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ownerLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(locationLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuisineLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(truckNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuisineTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(truckNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTruckBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateTruckBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteTruckBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewStackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewQueueBtn)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(truckNameLbl)
                            .addComponent(truckNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuisineLbl)
                            .addComponent(cuisineTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLbl)
                            .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ownerLbl)
                            .addComponent(ownerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regNoLbl)
                            .addComponent(regNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionLbl)
                            .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTruckBtn)
                    .addComponent(viewAllBtn)
                    .addComponent(viewStackBtn)
                    .addComponent(viewQueueBtn)
                    .addComponent(updateTruckBtn)
                    .addComponent(deleteTruckBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTruckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTruckBtnActionPerformed
        // TODO add your handling code here:
        String name = truckNameTF.getText();
        String cuisine = cuisineTF.getText();
        String location = locationTF.getText();
        String owner = ownerTF.getText();
        String reg = regNoTF.getText();
       

        if (name.isEmpty() || cuisine.isEmpty() || location.isEmpty() || owner.isEmpty() || reg.isEmpty()) {
            displayTextArea.setText("Please fill in all fields!");
        } else {
            FoodTruck ft = new FoodTruck(reg, owner, name, cuisine, location);
            truckList.add(ft);
            truckStack.push(ft);
            clearFields();
            displayTextArea.setText("Truck added successfully!\nTotal trucks: " + truckList.size());
        }
    }//GEN-LAST:event_addTruckBtnActionPerformed

    private void truckNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_truckNameTFActionPerformed

    private void deleteTruckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTruckBtnActionPerformed
        // TODO add your handling code here:
        String name = truckNameTF.getText();
        boolean found = false;

        for (int i = 1; i <= truckList.size(); i++) {
            FoodTruck ft = (FoodTruck) truckList.get(i);
            if (ft.getTruckName().equalsIgnoreCase(name)) {
                truckList.remove(i);
                clearFields();
                displayTextArea.setText(name + " removed successfully!\nTotal trucks: " + truckList.size());
                found = true;
                break;
            }
        }
        if (!found) {
            displayTextArea.setText(name + " not found in the system.");
        }
    }//GEN-LAST:event_deleteTruckBtnActionPerformed

    private void viewAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBtnActionPerformed
        // TODO add your handling code here:
        if (truckList.isEmpty()) {
            displayTextArea.setText("No trucks in the system.");
        } else {
            displayTextArea.setText("All Food Trucks\n" + truckList.displayList());
        }
    }//GEN-LAST:event_viewAllBtnActionPerformed

    private void updateTruckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTruckBtnActionPerformed
        // TODO add your handling code here:
        String posText = positionTF.getText();

        if (posText.isEmpty()) {
            displayTextArea.setText("Please enter a position to update.");
        } else {
            int pos = Integer.parseInt(posText);
            if (pos < 1 || pos > truckList.size()) {
                displayTextArea.setText("Invalid position. List has " + truckList.size() + " trucks.");
            } else {
                String name = truckNameTF.getText();
                String cuisine = cuisineTF.getText();
                String location = locationTF.getText();
                String owner = ownerTF.getText();
                String reg = regNoTF.getText();
                FoodTruck updated = new FoodTruck(reg, owner, name, cuisine, location);
                truckList.update(pos, updated);
                clearFields();
                displayTextArea.setText("Truck at position " + pos + " updated successfully!");
            }
        }
    }//GEN-LAST:event_updateTruckBtnActionPerformed

    private void viewStackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStackBtnActionPerformed
        // TODO add your handling code here:
        if (truckStack.isEmpty()) {
            displayTextArea.setText("Stack is empty.");
        } else {
            displayTextArea.setText("-- Recently Added Trucks (Stack) --\n" + truckStack.displayStack());
        }
    }//GEN-LAST:event_viewStackBtnActionPerformed

    private void viewQueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQueueBtnActionPerformed
        // TODO add your handling code here:
        if (orderQueue.isEmpty()) {
            displayTextArea.setText("No orders in queue.");
        } else {
            displayTextArea.setText("-- Order Queue --\n" + orderQueue.displayQueue());
        }
    }//GEN-LAST:event_viewQueueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTruckBtn;
    private javax.swing.JLabel cuisineLbl;
    private javax.swing.JTextField cuisineTF;
    private javax.swing.JButton deleteTruckBtn;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JTextField locationTF;
    private javax.swing.JLabel ownerLbl;
    private javax.swing.JTextField ownerTF;
    private javax.swing.JLabel positionLbl;
    private javax.swing.JTextField positionTF;
    private javax.swing.JLabel regNoLbl;
    private javax.swing.JTextField regNoTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel truckNameLbl;
    private javax.swing.JTextField truckNameTF;
    private javax.swing.JButton updateTruckBtn;
    private javax.swing.JButton viewAllBtn;
    private javax.swing.JButton viewQueueBtn;
    private javax.swing.JButton viewStackBtn;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        truckNameTF.setText("");
        cuisineTF.setText("");
        locationTF.setText("");
        ownerTF.setText("");
        regNoTF.setText("");
        positionTF.setText("");
    }

}
